[general]
name = "minilib-text"
version = "0.8.2"
fix_version = "1.3.0"
authors = ["pt9999"]
license = "MIT"

[build]
opt_level = "basic"
files = [
    "lib/text/locale.fix",
    "lib/text/simple_parser.fix",
    "lib/text/unicode.fix",
    "lib/text/wide_char.fix",
    "lib/text/wparser.fix",
]
objects = ["lib.o"]
preliminary_commands = [["make", "lib.o"]]

[build.test]
opt_level = "basic"
files = [
    "tests/test.fix",
    "tests/text/locale_test.fix",
    "tests/text/simple_parser_test.fix",
    "tests/text/unicode_test.fix",
    "tests/text/wide_char_test.fix",
    "tests/text/wparser_test.fix",
]

[[dependencies]]
name = "minilib-common"
version = "0.12.0"
# path = "../fixlang-minilib-common"
git = { url = "https://github.com/pt9999/fixlang-minilib-common.git" }
